# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae50b4ff28d85857ef49a77b00e93a430936efd92c1b6611f2fe5baedaa0014a5b4e951a5ee06bb8d3e826c43a96fef73f46acb48a7b8c74d4caa97f8c8141c7


test:
  secret_key_base: aaec763fca5a6baeea0e85a5a06ed648bd12fd7a80ee910c275d11f33c3a5f1b0655dea89e00ebca5b31fdacf6053bb1176e27d61cef8e3a313e26b4dda3225b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
